version: 2
jobs:
  build:
    working_directory: ~/georama
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec
